[I 19:36:35.925 NotebookApp] [nb_conda_kernels] enabled, 12 kernels found
[I 19:36:36.261 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 19:36:39.338 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 2023-03-21 19:36:43.463 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-03-21 19:36:43.469 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-21 19:36:43.469 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-21 19:36:43.469 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-21 19:36:43.469 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-21 19:36:43.469 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-21 19:36:43.470 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-21 19:36:43.471 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-03-21 19:36:43.480 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2023-03-21 19:36:43.482 LabApp] JupyterLab extension loaded from /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/jupyterlab
[I 2023-03-21 19:36:43.482 LabApp] JupyterLab application directory is /om/user/leokoz8/envs/add_RL/share/jupyter/lab
[I 19:36:43.488 NotebookApp] Serving notebooks from local directory: /rdma/vast-rdma/vast/fiete/leokoz8/code/add_RL
[I 19:36:43.488 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 19:36:43.488 NotebookApp] http://node074:9000/
[I 19:36:43.488 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:40:10.929 NotebookApp] 302 GET / (172.16.24.254) 0.850000ms
/om/user/leokoz8/envs/add_RL/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 19:40:30.833 NotebookApp] Notebook notebooks/fan_task_test.ipynb is not trusted
Exception in callback <TaskWakeupMethWrapper object at 0x2b5d17a0c640>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b5d17a0c640>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/add_RL/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-9' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/add_RL/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
[I 19:40:32.431 NotebookApp] Kernel started: 4f7a19e9-9cb7-43ae-8a18-a8ccc1a107ab, name: conda-env-leokoz8-add_RL-py
/om/user/leokoz8/envs/add_RL/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 20:18:32.312 NotebookApp] Saving file at /notebooks/fan_task_test.ipynb
[W 20:18:32.314 NotebookApp] Notebook notebooks/fan_task_test.ipynb is not trusted
[I 20:20:25.304 NotebookApp] Saving file at /notebooks/fan_task_test.ipynb
[W 20:20:25.306 NotebookApp] Notebook notebooks/fan_task_test.ipynb is not trusted
[I 20:20:25.676 NotebookApp] Saving file at /notebooks/fan_task_test.ipynb
[W 20:20:25.677 NotebookApp] Notebook notebooks/fan_task_test.ipynb is not trusted
[I 20:20:26.989 NotebookApp] Starting buffering for 4f7a19e9-9cb7-43ae-8a18-a8ccc1a107ab:7e35b5b0cd634799887b7134a514710d
[I 20:20:31.504 NotebookApp] Copying notebooks/fan_task_test.ipynb to /notebooks
[W 20:20:31.546 NotebookApp] Notebook notebooks/fan_task_test.ipynb is not trusted
[W 20:20:31.549 NotebookApp] Notebook notebooks/fan_task_test-Copy1.ipynb is not trusted
[W 20:20:55.147 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:20:56.052 NotebookApp] Kernel started: 6fb2b490-bab9-4eed-93e7-5278545334d4, name: conda-env-leokoz8-add_RL-py
[I 20:22:56.360 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:22:56.361 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:24:56.360 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:24:56.361 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:26:56.359 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:26:56.359 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:30:56.066 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:30:56.068 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:32:56.065 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:32:56.069 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:34:56.059 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:34:56.060 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:36:56.066 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:36:56.067 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:38:56.083 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:38:56.085 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:40:56.071 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:40:56.073 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:42:56.071 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:42:56.073 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:44:56.078 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:44:56.079 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:46:56.380 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:46:56.381 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:54:56.131 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:54:56.131 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:56:56.105 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:56:56.106 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 20:58:56.088 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 20:58:56.089 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 21:00:56.102 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 21:00:56.103 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 21:02:56.082 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 21:02:56.083 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
[I 21:04:56.374 NotebookApp] Saving file at /notebooks/Q_lambda_fan.ipynb
[W 21:04:56.375 NotebookApp] Notebook notebooks/Q_lambda_fan.ipynb is not trusted
slurmstepd: error: *** JOB 29931036 ON node074 CANCELLED AT 2023-03-22T07:36:39 DUE TO TIME LIMIT ***
